# container ที่อยู่ใน Docker-compose เดียวกันสามารถคุยกันได้ผ่าน networkname ex lb, mynginx1
version: "3"
services:
  lb:
    image: 3dsinteractive/nginx:1.12
    # ให้สร้าง mynginx1 และ mynginx2 ก่อน
    depends_on:
      - mynginx1
      - mynginx2
      - mynginx3
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    # map volume เพื่อ config
    volumes:
      - ./dockers/lb/logs:/opt/bitnami/nginx/logs
      - ./dockers/lb/nginx:/bitnami/nginx
  mynginx1:
    image: paretk/mynginx:1.0
  mynginx2:
    image: paretk/mynginx:1.0
  mynginx3:
    image: paretk/mynginx:1.0
